name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show Python version (just a demo step)
        run: python --version

      - name: Say Hello from Django CI
        run: echo "✅ CI is working!"
